CognitiveVR/cvr-sdk-unity

Runtime/Components/AnalyticsComponentBase.cs
Runtime/Components/ArmLength.cs
Runtime/Components/BatteryLevel.cs
Runtime/Components/BoundaryEvent.cs
Runtime/Components/Comfort.cs
Runtime/Components/ControllerCollisionEvent.cs
Runtime/Components/ControllerInputTracker.cs
Runtime/Components/Framerate.cs
Runtime/Components/HMDCollisionEvent.cs
Runtime/Components/HMDHeight.cs
Runtime/Components/OcclusionEvent.cs
Runtime/Components/OculusSocial.cs
Runtime/Components/RecenterEvent.cs
Runtime/Components/RoomSize.cs
Runtime/Components/ScreenResolution.cs
Runtime/Components/TeleportEvent.cs
Runtime/Scripts/Cognitive3D_Manager.cs
Runtime/Scripts/GPSLocation.cs

Made components that inherit from Analytics Component Base subscribe to the OnSessionBegin event in OnEnable, and removed initialize call from Cognitive Manager. Should work more consistently for strange startup orders and sequential sessions.

fixed bug with components calling start twice

---

Runtime/Components/BatteryLevel.cs

Send HMD Battery level as sensor every 1 second if a standalone device build.
Height Task ID (If applicable): https://c3d.height.app/current-sprint/T-1042
- [ N/A] I have commented my code, particularly in hard-to-understand areas
- [ N/A] I have made corresponding changes to the documentation

Feature battery sensor

---

Runtime/Scripts/Cognitive3D_Manager.cs

We are sending battery level (if XRPF approved) on session start and session pause events. We can't yet determine end session properly, so we might have to either do backend magic or some plugin work to determine when the session ends.
Please use "AtifTesting" app Version 1002 on your Quest 2 for testing.
Height Task ID (If applicable): T-1796

Developer controlled sending battery level on start and pause

---

Editor/ExitPollHolderInspector.cs
Runtime/ExitPoll/ExitPoll.cs

Unity VSP reported a bug where "ExitPoll cannot be interacted with when Pointer Type is set to HMD". We believe it was because of a bug which allowed users to misconfigure exit poll. This PR fixes that by prevent users from picking pointer parents which make no sense in context of pointer type (or vice versa).
Notion Doc to track Atif's VSP work: https://www.notion.so/cognitive3d/Atif-s-VSP-Stuff-345ec5e492ac4074ae0e2bb2ad6f1d71
Height Task ID (If applicable): T-1915

VSP Test Case 54: Exit Poll w/ HMD

---

Runtime/Components/TeleportEvent.cs

The `Teleport Event` script previously calculated the distance moved by the top-most parent A.K.A `root` of the camera. This assumes that the root will move. However in some cases, the root doesn't move, but an intermediate parent does.
This PR fixes that bug.
Height Task ID (If applicable): https://c3d.height.app/sdk/T-1989

Fix teleport event

---

Runtime/ActiveSessionView/ActiveSessionView.prefab

Longer sensor names used to overlap. This issue has been fixed. To test, please pull from this branch and test out the ActiveSessionView prefab in your scene with sensor names of different sizes.
Height Task ID (If applicable): T-1992

Active session view

---

Runtime/Components/BoundaryEvent.cs

Height Task ID (If applicable): https://c3d.height.app/current-sprint/T-1977
We are now able to get events when user exits VR guardian. NOTE: Currently only works on Oculus.
To test, please run sessions using the AtifTesting app, Version 1049.

Events on VR Guardian Exits

---

Runtime/Scripts/Cognitive3D_Manager.cs

Unloading additive scenes was causing problems with tracking ID. As part of this task, we improved the overall implementation of scene management for both additive and single, encompassing scenes with and without ID. 
This improvement will allow us to tackle and handle various scenarios w.r.t scene loading/unloading.
Notes on notion: https://www.notion.so/cognitive3d/Unity-Scene-Load-8a9f21d53fa94964bde44540f073ac8d?pvs=4
Height Task ID (If applicable) :https://c3d.height.app/current-sprint/T-578

Improvements to Scene Load/Unload

---

Runtime/Components/ControllerInputTracker.cs

We were recording press events when joystick was touched. This was due to leftover code from touchpad implementation. This PR fixes that.
Height Task ID (If applicable): https://c3d.height.app/T-2297
Notion: https://www.notion.so/cognitive3d/T-2297-Remove-Touch-events-from-joystick-inputs-793a8cac8a6143f690a348a2e4e22a58?pvs=4

Fix controller touch

---

Editor/DynamicObjectsWindow.cs

The Dynamic Object Window was losing focus because of the confirmation and upload progress modals. That didn't update the upload status and led to confusion. The fix makes the window gain back focus and as a result, the upload status updates. 
To test, please checkout this branch and try creating and uploading a few dynamic objects. Works on my machine.
Height Task ID (If applicable): https://c3d.height.app/T-1980

[FIX] Focus restored on Dynamic Object Window after upload complete

---

Runtime/Scripts/FixationRecorder.cs
Runtime/Scripts/GazeHelper.cs
Runtime/Scripts/GazeReticle.cs

Simplified and fixed PicoXR SDK gaze direction calculation. It was using local rotation and position and not converting that into world space before calculating fixation points.
Height Task ID (If applicable): 3018

fixed fixation direction math for picoxr

---

Editor/SceneSetupWindow.cs

Adding information and a button link to documentation about Session Tags at the end of Scene Setup Screens.
Height Task ID (If applicable): https://c3d.height.app/T-3075

Improvement onboarding sessiontag

---

Runtime/ExitPoll/ExitPoll.cs
Runtime/Internal/NetworkManager.cs
Runtime/Scripts/Cognitive3D_Manager.cs
Runtime/Scripts/MicrophoneButton.cs
Runtime/Scripts/MicrophoneUtility.cs
package.json

* Automatically skip Exitpoll voice questions when targeting WebGL
* Generate a unique DeviceId from a Guid when targeting WebGL
* Added cvr-request-time header if not present for WebGL builds

Webgl microphone hotfix

---

Runtime/ExitPoll/ExitPoll.cs
Runtime/ExitPoll/ExitPollPanel.cs

Fixing question progress marker in ExitPollPanel, i.e. Question X out of Y. This was reported by customers and was initially mistaken as an issue pertaining to ExitPoll initialization.

Fixing incorrect Question X out of Y issue

---

Editor/SceneSetupWindow.cs
Runtime/Components/RoomSize.cs
Runtime/Components/RoomTrackingSpace.cs
Runtime/Components/RoomTrackingSpace.cs.meta
Runtime/Scripts/Cognitive3D_Manager.cs
Runtime/Scripts/GameplayReferences.cs
package.json

This change encapsulates the following:
- Fix for SteamVR boundary implementation
- Adding generic Unity XR API implementation for boundary
- Adding event for when user recenters
- Code cleanup
Requires heavy testing on Oculus, SteamVR, Unity Generic XR for boundary exits, boundary changes, and recenters.
Height Task ID (If applicable): https://c3d.height.app/T-3473  ||  https://c3d.height.app/T-4053

Improvements to Boundary Event

---

Editor/EditorCore.cs

- Fix for Unity Export Dynamic Object count bug
- Removed the cached value in EditorCore.cs
Height Task ID (If applicable): https://c3d.height.app/T-4420

Fix for Unity Export Dynamic Object count bug

---

Runtime/ActiveSessionView/Scripts/ActiveSessionView.cs
Runtime/ActiveSessionView/Scripts/CopyVRViewToRenderTexture.cs
Runtime/ActiveSessionView/Scripts/DataBatchCanvas.cs
Runtime/ActiveSessionView/Scripts/DynamicSortable.cs
Runtime/ActiveSessionView/Scripts/EventCanvas.cs
Runtime/ActiveSessionView/Scripts/EventFeedEntry.cs
Runtime/ActiveSessionView/Scripts/FullscreenDisplay.cs
Runtime/ActiveSessionView/Scripts/MetaCanvas.cs
Runtime/ActiveSessionView/Scripts/RenderEyetracking.cs
Runtime/ActiveSessionView/Scripts/SensorCanvas.cs
Runtime/ActiveSessionView/Scripts/SensorRenderCamera.cs

- Hide internal monobehaviour scripts from Unity
- Add the [AddComponentMenu("")] attribute to the classes (Runtime/Internal and Runtime/ActiveSessionView related scripts)
Height Task ID (If applicable): https://c3d.height.app/T-3061

Removed access to internal monobehaviour scripts from Unity

---

Runtime/Internal/SensorRecorder.cs
Runtime/Internal/Serialization/CoreInterface.cs
Runtime/Internal/Serialization/SharedCore.cs

- Added initialization for sensor data
- Setting sensor data initialization in SharedCore.cs
Height Task ID (If applicable): https://c3d.height.app/T-3758

Fix for missing sensor metadata

---

Runtime/Components/OculusSocial.cs

`OculusSocial.cs` was causing exceptions if the platform initialization failed. This exception caused problems in serializing data, and caused sessions to be 0 seconds long. I moved some risky code (risky only in the sense that it can fail if initialization fails) into the `try` block. This seems to have fixed the issue.
Note: If initalization fails, not Oculus Social data will be collected, but at least we won't have the app record nothing. It will gracefully fail.
Height Task ID(s) (If applicable): https://c3d.height.app/T-4486

Fixed Exception in OculusSocial

---

Editor/SceneSetupWindow.cs
Runtime/Components/HandTracking.cs
Runtime/Components/HandTracking.cs.meta

Incrementally building towards hand tracking support, we are sending sensors for whether participant is using hands, controllers, or none. We are also sending events when they switch between hands and controllers.
For the sensors:
- 0 = None
- 1 = Controller
- 2 = Hand
Session with example: https://app.cognitive3d.com/scenes/3fdf2fd6-4d2d-405b-b638-d6d619ebcc96/v/19/session/1201395
https://github.com/CognitiveVR/cvr-sdk-unity/assets/14244062/d8221a17-4303-4f78-bf47-8ddbdf2aa87b
Height Task ID(s) (If applicable): https://c3d.height.app/T-4643

Sensors and Events for Hands -vs- Controllers

---

Runtime/Components/ProfilerSensor.cs

Height Task ID(s) (If applicable): https://c3d.height.app/T-4195
This is associated with the Profiler Sensor task. We weren't including units for the sensors. This PR fixes that.
- [] I have made corresponding changes to the documentation

Added units for profiler sensors

---

Runtime/Components/ProfilerSensor.cs

Testing with Unity 2019.4 revealed that the ProfilerRecorder only exists above 2020.2. This change puts scripting defines to ensure compilation isn't failing on older versions.
Height Task ID(s) (If applicable): N/A

Using scripting symbols for `ProfilerRecorder`. Only available for Unity >= 2020.2

---

Runtime/Components/HMDOrientation.cs

- Calculates the yaw value according to the tracking space
- Calculation fix for recording yaw by isolating HMD rotation from tracking space rotation
Height Task ID(s) (If applicable): https://c3d.height.app/T-4190

Fix for incorrect HMD yaw calculation

---

Editor/Setup360Window.cs

The "Refresh Media Sources" button on the `360 Setup` window could only be clicked once. However the `Refresh` button on the `Media Component` persists. This change updates the `360 Setup Window` to follow the same behaviour. 
The following GIFs showcase behaviour before and after the change.
Height Task ID(s) (If applicable): https://c3d.height.app/T-4691
- [N/A] I have commented my code, particularly in hard-to-understand areas

`Refresh Media Sources` button behaviour in 360 Setup Window

---

Runtime/Components/ProfilerSensor.cs

To prevent the SDK from sending too many frequent web requests, we are reducing the frequency of profiler sensor to 1Hz from default 10Hz.
Height Task ID(s) (If applicable): https://c3d.height.app/T-4779

Updating Profiler Sensor to 1Hz

---

Runtime/Components/OculusSocial.cs

Removed Party Size from Oculus Social because it wasn't being used
Height Task ID(s) (If applicable): https://c3d.height.app/T-4897

Remove PartySize from OculusSocial component

---

Editor/DynamicObjectInspector.cs
Editor/DynamicObjectsWindow.cs
Runtime/Scripts/DynamicObject.cs

In Unity SDK - user wasn't able to select `Pool ID` as an option for ID Source for Dynamic Objects. This PR fixes that issue.
https://www.loom.com/share/1c6aebb55c19443a97f73f30b71258e6?sid=7e14b649-3450-4fb3-9f07-e84f9a441e1b
Height Task ID(s) (If applicable): https://c3d.height.app/T-4869

Fix for Dynamic `ID Source` Selection

---

Runtime/Components/ControllerTracking.cs

We were getting multiple back to back `Controller Lost Tracking` events. This usually happened when controllers went out of, and back in tracking range quickly within a short time. Also happened when controllers were at 90 degrees from HMD. 
We are now introducing a cooldown period, so we don't have multiple lost events repeatedly. Also, to get an idea of what angle causes controller lost events, we have an angle as an event property.
Height Task ID(s) (If applicable): 
- https://c3d.height.app/T-5097
- https://c3d.height.app/T-5098

Updating ControllerTracking to prevent multiple repeated events; adding angle and height as a event property

---

Runtime/Internal/NetworkManager.cs

Changed NetworkManager to include delays for 500 response retries and emptying cache:
- Added 2 seconds delay when uploading local cache data once connectivity is returned (Changed CACHEDResponseCallback() to an asynchronous function)
- Added progressive wait times when response codes are 500 or 0 (when WIFI is off)
- Resetting the progressive wait time to 1 minute once response code is 200 (Min wait time: 1 minute, Max wait time: 4 minutes)
Height Task ID(s) (If applicable): https://c3d.height.app/T-5070 , https://c3d.height.app/T-5030

Progressive wait times for retries on 500 responses and introduced delays for cache data web requests

---

Runtime/Scripts/DynamicObject.cs

- Seems like it was an error in translating logic to enums during refactoring
- Changed source ID type in if statement to PoolID (line 227)
Height Task ID(s) (If applicable): https://c3d.height.app/T-5075

Fix for incorrect reference of IdPool for Generated ID

---

Editor/ExportUtility.cs
Editor/GLTF/GLTFSceneExporter.cs
Runtime/Scripts/CustomRenderExporter.cs

Changed CustomRenderExporter component to include exporting child meshes. Also added:
* URP support (must be set per component in the scene)
* Basic lod support (highest resolution only)
* Option to bake textures from topdown only, decreasing export time
* Fixed filename escaping with ':'
Height Task ID(s) (If applicable): T-4981

Include Child Meshes with CustomRenderExporter Script

---

Runtime/Components/OculusSocial.cs

We are simplifiyng the options on the `OculusSocial` component. This includes renaming the variables, simplifying to one toggle, and making it default to `true`.
Height Task ID(s) (If applicable): https://c3d.height.app/T-4864

Simplify oculus social

---

Runtime/Components/ArmLength.cs
Runtime/Scripts/GameplayReferences.cs

To make the `ArmLength` component more robust and prevent incorrect or misleading values, we are going to check if the controller is tracked before we use it's position to record arm length.
Height Task ID(s) (If applicable): https://c3d.height.app/T-5255

Check controller tracking before recording armlength

---

Runtime/Components/OculusHardware.cs

The following changes are made to fix "No Active Oculus Display Subsystem Found" error:
- Implemented `GetActiveDisplaySubsystem()` to retrieve the active display subsystem.
- Check to verify if the active display subsystem is` Oculus`. In the case of `OpenXR`, `Oculus hardware` data collection is skipped, and a warning is logged in the console (displayed only once at the start of the session).
- Added a 1-second delay before checking the active display subsystem
- Fixed a misspelling in `GetDescription()`
Height Task ID(s) (If applicable): https://c3d.height.app/T-4946

Fix for No Active Oculus Display Subsystem Found

---

Runtime/Components/HandTracking.cs

Height Task ID(s) (If applicable): https://c3d.height.app/T-5286, https://c3d.height.app/T-5316
We are removing the sensor stream representing hands-vs-contoller. In addition, we are adding an event on `SessionBegin()` so we can track controller events from beginning to end.

HandTracking: Remove sensor; improve events

---

Editor/EditorCore.cs
Editor/SceneSetupWindow.cs

We are improving the quality of scene thumbnail from `256x256` to `1024x432`. This change also includes improvements to the scene setup window for a better UX.
Height Task ID(s) (If applicable): https://c3d.height.app/T-5589

Increase scene thumbnail size; UI changes

---

Runtime/Components/OculusHardware.cs

In Unity 2020.1 and earlier versions, `OculusHardware.cs` throws a compile error. The function GetSubsystems() is not supported in Unity versions older than 2020.2.
- Added GetInstances() for the older versions of Unity which has the same functionality as GetSubsystems()
Height Task ID(s) (If applicable): https://c3d.height.app/T-5471

Fix for OculusHardware compile error

---

Editor/SceneSetupWindow.cs
Runtime/Components/HandTracking.cs
Runtime/Scripts/DynamicObject.cs
Runtime/Scripts/GameplayReferences.cs

If an app has hand tracking enabled, and a session uses hands only, and controller dynamic objects are set to `IdentifyControllerAtRuntime`, the objects will never get registered, leading to the session having no dynamics on dashboard and SE. This is a workaround for that situation, currently only for Oculus, but this will likely evolve as other platforms are introduced.
- In `DynamicObject.OnEnable()`, if hantracking is enabled, and currently using hands, use fallback controller mesh
- Current tracking type (using our own enum which we use for simplicity) now moved to `GameplayReferences.cs` so `DynamicObject.cs` can access it
- Created function for registering fallback controller and returning the name
Height Task ID(s) (If applicable): https://c3d.height.app/T-5438

Fix dynamic for hand tracking

---

Editor/SceneSetupWindow.cs

The checkbox state was always starting at `false`. It has been fixed to initialize to whe actual current state, i.e whether or not the components are actually there on `Cognitive3D_Manager`
Height Task ID(s) (If applicable): https://c3d.height.app/T-5622

Fix to meta component checkbox state

---

Runtime/Scripts/DynamicObject.cs

This enables a way to have consistent custom ids for dynamic objects. Developers can enable this option by adding `C3D_USE_DETERMINISTIC_DYNAMIC_ID` in the project settings or in the Cognitive3D runtime assembly definition file.
This algorithm uses SHA-256 with the mesh name as an input. The first 32 characters of the output is taken and formatted. 
Examples of mesh names and corresponding ids:
1. `capsule` : `881df12b-68cd-344e-83f6-b83d6e0eea5`
2. `sphere:` :  `0f58b78b-c54e-0c3e-5556-8ec522fb67b`
If `C3D_USE_DETERMINISTIC_DYNAMIC_ID` not added, the custom id option will use a GUID which will be different every time.
Height Task ID(s) (If applicable): https://c3d.height.app/T-3609

Consistent dynamic id using SHA 256

---

Runtime/Components/ControllerTracking.cs

Every controller lost tracking event should have a controller regained event. This will allow these events to define a time window in which the controllers are "lost" - this in turn will help SE disable/grey out controllers and hands to convey that information.
Height Task ID(s) (If applicable): https://c3d.height.app/T-5816

Events for controller regained

---

Runtime/Scripts/Cognitive3D_Manager.cs
Runtime/Scripts/FixationRecorder.cs
Runtime/Scripts/GameplayReferences.cs
Runtime/Scripts/GazeHelper.cs
Runtime/Scripts/GazeReticle.cs

* Moved OVRPluign.StartEyeTracking to CognitiveVR_Manager from FixationRecorder
* Removed OVRPlugin.eyeTrackingEnabled from checking if eye tracking was enabled. This is not set immediately after calling OVRPluign.StartEyeTracking
* Check user permissions before trying to enable the eye tracking feature
Height Task ID(s) (If applicable): T-5618

Quest Pro Eyetracking Fix

---

Runtime/Components/HMDOrientation.cs
Runtime/Components/RoomSize.cs
Runtime/Internal/Util.cs
Runtime/Scripts/Cognitive3D_Manager.cs

The following changes made to add a functionality and utility to display any logs once in the console to prevent overwhelming developers by repeated messages:
- Implemented `LogOnce()` with two parameters that handles logging messages only once
- Defined a hash set to track logged messages within a scene
- Reset the log hash set upon loading a new scene in single mode
- Used one-time logging in `HMDOrientation.cs` and `RoomSize.cs`
Height Task ID(s) (If applicable): https://c3d.height.app/T-5782

One-time logging utility

---

Editor/EditorCore.cs
Editor/EditorUtils.cs
Editor/EditorUtils.cs.meta

Displaying a popup after 15 minutes of inactivity
- Added `EditorUtils.cs` under `Runtime` for managing inactivity-related functionalities
- Handling 15 minutes wait time after user unmounts headset
- Added a 20-minute waiting period for user response after displaying the popup
- Updated `EditorCore.cs` to subscribe to the user activity checking process when entering Unity Editor play mode
Height Task ID(s) (If applicable): https://c3d.height.app/T-4771

Inactivity Popup Feature in Unity Editor

---

Runtime/Components/HMDOrientation.cs
Runtime/Components/RoomSize.cs
Runtime/Components/RoomTrackingSpace.cs
Runtime/Scripts/Cognitive3D_Manager.cs

With new changes, tracking space is handled through `RoomTrackingSpace.cs` and `Cognitive3D_Manager.cs`:
- Created `cachedTrackingSpaceList` and `trackingSpaceIndex` to keep track of tracking spaces
- Implemented `UpdateTrackingSpace()` in `Cognitive3D_Manager.cs` for dynamically updating the tracking space based on the list's status
- Reset the list and index during single mode scene loading and in `ResetSessionData()`
- In `RoomTrackingSpace.cs`, each component assigned an index which will be sent with `TrackingSpaceChanged` event and 
- When a component is disabled, a null value is sent along with the component index to be removed from the list
Height Task ID(s) (If applicable): https://c3d.height.app/T-5865
- [N/A ] I have made corresponding changes to the documentation
- [N/A ] Any …

TryGetTrackingSpace refactor

---

Runtime/Components/OculusHardware.cs

- Checking if the current subsystem isn't null before checking it's id
Height Task ID(s) (If applicable): https://c3d.height.app/T-5991
- [N/A] I have commented my code, particularly in hard-to-understand areas

Fix for NullReferenceException in Oculus Hardware

---

Runtime/Scripts/Cognitive3D_Manager.cs

The following describes changes made in Cognitive3D_Manager.cs for scene changing events:
- Removed `IsNextSceneValid()` and `DoesSceneHaveID()`
- Added `TryGetTrackedScene()` to check the scene in C3D scene settings
- Turned `SetTrackingScene()` methods into a single method and it only handles setting the tracking scene if it exist in C3D scene settings
- Added `SendSceneUnloadEvent()` and `SendSceneLoadEvent()` to handle scene change events
- Replacing `sceneStartTime` variable with `sceneStartTimeDic` dictionary. This was implemented for additive scene cases where `sceneStartTime` was getting repopulated when a new additive scene got loaded.
- Replaced `CustomEvent.Send(`) with `CustomEvent.Send(vector3 position)` for load and unload events. This will fix "No HMD found" error between …

Scene change event refactor

---

Editor/EditorCore.cs
Editor/UpdateSDKWindow.cs

A button in the update version window that links to the docs page. This is what it looks like.
Height Task ID(s) (If applicable): https://c3d.height.app/T-2608

Version Update Window: Button to link to docs website

---

Runtime/Components/OculusSocial.cs

Fix for oculus entitlement so developers can choose when entitlement check happens.
Testing docs in notion: https://www.notion.so/cognitive3d/Oculus-Social-Testing-delayed-entitlement-check-07b8d27ffbdd4db0a5311a3eefd7ce51?pvs=4
Height Task ID(s) (If applicable): https://c3d.height.app/T-6191

Oculus entitlement fix

---

Runtime/Components/Framerate.cs

Because of ASW, framerate is capped at 36. This causes problems with our analytics and metrics, but doesn't cause any discomfort for user because of "synthetic frames". This change corrects our framerate data collection to account for ASW.
Details can be found on [this notion doc](https://www.notion.so/cognitive3d/Async-Space-Warp-4f9015ccf11f4ac281bdfb9649c8031a?pvs=4)
Height Task ID(s) (If applicable): https://c3d.height.app/T-6058

Adjusting framerate for ASW

---

Editor/ProjectValidation/Items/ProjectValidationItems.cs

The following changes are made to fix the bug:
- improved the handling of `XROrigin` and `CameraOffset `components in both `checkAction` and `fixAction` to prevent their values from resetting when entering and exiting play mode.
- Improved checks for null values
- Removed `xrorigins[0].CurrentTrackingOriginMode` in the condition, as it consistently returns `Unknown` value
- Refined `checkAction` to focus solely on verifying if the tracking origin is set to Floor in the associated component's dropdown
Height Task ID(s) (If applicable): https://c3d.height.app/T-6690
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the …

Fix for project validation OpenXR tracking origin bug

---

Editor/SceneSetupWindow.cs
Runtime/Components/HMDHeight.cs

Improves the scene setup window to automatically identify and assign the `TrackingSpace` object where possible. Also adds functionality to detect controllers for some setups.
Notes for testing can be found here: https://www.notion.so/cognitive3d/T-6639-UX-for-TrackingSpace-c387a3683474447594f4684b0efa867a?pvs=4
Height Task ID(s) (If applicable): https://c3d.height.app/T-6639

Auto assign room tracking

---

Runtime/Components/HandTracking.cs
Runtime/Scripts/DynamicObject.cs
Runtime/Scripts/GameplayReferences.cs

Controllers weren't being added to manifest if you use only hands or none. Details can be found in the notion doc: https://www.notion.so/cognitive3d/T-6858-Hand-tracking-doesn-t-register-dynamic-object-for-controllers-62b023d1c105462592d3d548fac0e5f6?pvs=4
Height Task ID(s) (If applicable): https://c3d.height.app/T-6858

[T-6858] Hand tracking doesn’t register dynamic object for controllers

---

Editor/EditorUtils.cs

The following changes are made for inactivity popup:
- Checking GameplayReference HMD movement for user inactivity (for all SDKs) which should cover all edge cases
Notion doc for tests (Testing New Inactivity Approach): https://www.notion.so/cognitive3d/User-Inactivity-Popup-17d3827d61fc42948aff140efd67b3ef
- [N/A] I have checked all outgoing links (i.e. to documentation) for validity

User inactivity popup update

---

Runtime/Components/ArmLength.cs

To prevent false values, we are clamping armlength to positive values less than 1.25m
Height Task ID(s) (If applicable): https://c3d.height.app/T-5864

Arm length should be positive and less than 1.25m

---

Editor/Cognitive3DEditor.asmdef
Editor/SceneSetupWindow.cs
Runtime/Cognitive3D.asmdef
Runtime/Components/Cognitive3D_MetaSceneMesh.cs

Meta SDK version >= 65 does not support `OVRSceneManager` - it uses `MRUK`. This PR adds support for `MRUK`.
Tested functionality - it works.
Height Task ID(s) (If applicable):

MRUK support for floor area Meta SDK >= 65

---

Editor/ProjectValidation/Items/ProjectValidationItem.cs
Editor/ProjectValidation/Items/ProjectValidationItems.cs
Editor/ProjectValidation/ProjectValidation.cs
Editor/ProjectValidation/ProjectValidationGUI.cs

The following changes are made for a project validation item to ensure that each scene contains no more than 2 controller dynamic objects:
- Added a (required) validation item to check the number of controller dynamic objects in a scene.
- This validation item has no automatic fix action. Users must manually remove any additional dynamic object components.
- Updated `ItemAction` to include `None` enum for items without a fixAction.
- Implemented the `UpdateProjectValidationItemMessage` function for updating item's message. It checks for items containing the `oldmessage` and replaces it with `newmessage`.
Height Task ID(s) (If applicable): https://c3d.height.app/T-7856
- [N/A] Any dependent changes have been merged and …

Project Validation: Check Number of Controllers in Scene

---

Editor/SceneSetupWindow.cs

Changes to the scene upload UX to include an option to export dynamic objects in scene that have not been exported. Tested pretty much everything. A quick sanity check on the critical path will be appreciated.
Height Task ID(s) (If applicable): T-8106

Option to export new dynamics from scene in `UploadSummary`

---

Editor/DynamicObjectIdPoolInspector.cs
Editor/DynamicObjectInspector.cs
Editor/DynamicObjectsWindow.cs
Editor/EditorCore.cs

We need a way to filter out controllers from Scene Viewer. To that end, we are adding the `isController` field to the dynamic manifest.
Height Task ID(s) (If applicable): T-8490

Add `isController` variable to dynamic aggregation manifest

---

Editor/EditorCore.cs
Editor/ProjectValidation/Items/ProjectValidationItems.cs
Editor/ProjectValidation/Items/ProjectValidationItemsStatus.cs
Editor/ProjectValidation/ProjectValidation.cs
Editor/ProjectValidation/ProjectValidationBuildProcess.cs
Editor/ProjectValidation/ProjectValidationGUI.cs
Editor/ProjectValidation/ProjectValidationSettingsProvider.cs

The following updates introduce two new validation items for checking scene versions:
- Added a validation check in `ProjectValidationItems.cs` to ensure the latest version of a scene is used
- Implemented a check in `ProjectValidationItems.cs` to verify if a scene exists on the dashboard
- Added `RegenerateItems()` in `ProjectValidation.cs` to clear and rebuild the list of items
- Refactored logic and moved relevant code to `ProjectValidation.cs`, designating it as the core of project validation
Height Task ID(s) (If applicable): https://c3d.height.app/T-8771

Scene Version Validation Items

---

Editor/Cognitive3DEditor.asmdef
Editor/ProjectSetupWindow.cs
Editor/ProjectValidation/Items/ProjectValidationItems.cs
Editor/SceneSetupWindow.cs
Runtime/Cognitive3D.asmdef
Runtime/Components/NetcodeMultiplayer.cs
Runtime/Components/NetcodeMultiplayer.cs.meta

The following changes are made for Unity Netcode support:
- Added a `NetcodeMultiplayer` script to manage Netcode functionalities.
- Set lobby ID for the host and send it to clients upon connection, including it as a session property.
- Implemented connection and disconnection events for clients and the host using `OnClientConnectedCallback()` and `OnClientDisconnectCallback()`.
- Recorded the number of connected players through `SetConnectedCountServerRPC()` whenever connection or disconnection callbacks are triggered.
- Configured session properties for client ID, server address, and port with `SetMultiplayerSessionProperties()`.
- Added Netcode support option into the multiplayer page of project settings.
- Developed logic to add Netcode-related support scripts when the option is …

Unity Netcode Multiplayer Support

---

Editor/EditorDataUploader.cs
Runtime/Internal/DualFileCache.cs

This PR introduces changes to improve handling of empty lines and ensures valid content is read and written in the data files:
- Updated `MergeDataFiles()` to skip empty or whitespace-only lines when merging data from the write file into the read file.
- Improved `PeekContent()` to retry reading content after merging data files and return valid non-empty lines, with improved error handling for missing or invalid data.
- Added null checks for destination and content in `EditorDataUploader.cs`.
Height Task ID(s) (If applicable): https://c3d.height.app/T-8311

Fix for Empty Lines in Local Cache

---

Editor/ProjectValidation/Items/ProjectValidationItems.cs
Runtime/Scripts/FixationRecorder.cs
Runtime/Scripts/GazeHelper.cs

Here are the updates made to improve eye tracking for the Wave SDK:
- Fixed the snap turning bug where the rig rotation wasn't considered. This was addressed in both `FixationRecorder.cs` and `GazeHelper.cs` by transforming the eye point from local space to world space.
- Added a new "required" validation item to check the eye manager component in the scene.
Height Task ID(s) (If applicable): https://c3d.height.app/T-9088

Wave Eye Tracking Support Improvement

---

Editor/ProjectValidation/Items/ProjectValidationItems.cs
Editor/ProjectValidation/ProjectValidation.cs
Editor/ProjectValidation/ProjectValidationGUI.cs
Runtime/Components/HMDPresentEvent.cs
Runtime/Internal/GazeCore.cs

This PR addresses several minor bugs:
- Updated `GetFloorPosition()` to use the tracking space position for the floor position. It falls back to a raycast if no tracking space is found in the scene.
- Added a value check for `removedTimestamp` in `CheckUserPresence()` to fix the null reference exception at runtime.
- Added a validation item for invalid scene paths which checks for invalid paths in any opened active scene.
- Added `UNITY_ANDROID` condition to two validation items to fix the compiler error where the Android module is not installed in the Unity editor
Height Task ID(s) (If applicable):
https://c3d.height.app/T-9252
https://c3d.height.app/T-10451
https://c3d.height.app/T-10627

Minor Bug Fixes
