CognitiveVR/cvr-sdk-unity

- CognitiveVRUnity/Assets/CognitiveVR/Editor/EditorCore.cs
- CognitiveVRUnity/Assets/CognitiveVR/Editor/MenuItems.cs
- CognitiveVRUnity/Assets/CognitiveVR/Scripts/GazeBase.cs
- CognitiveVRUnity/Assets/CognitiveVR/Scripts/GazeButton.cs
- CognitiveVRUnity/Assets/CognitiveVR/Scripts/GazeReticle.cs
- CognitiveVRUnity/Assets/CognitiveVR/Scripts/MicrophoneButton.cs
Neurable Namespacing has changed in v1.4.0
Contact Neurable for Supported SDK Package
> WIP: Update Neurable Signatures

- CognitiveVRUnity/Assets/CognitiveVR/Editor/EditorNetwork.cs
- CognitiveVRUnity/Assets/CognitiveVR/Editor/ExportUtility.cs
- uploading scene
- uploading dynamic object
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
> Implemented cancelable progress bar for all web requests including:

- Runtime/Scripts/Cognitive3D_Manager.cs
- Runtime/Scripts/GazeBase.cs
- Runtime/Scripts/GazeHelper.cs
We are removing unused SDKs, The ones we removed are: C3D_AH, C3D_FOVE, C3D_NEURABLE, C3D_PUPIL and C3D_TOBIIVR
The files we removed them from are: Cognitive3DManager,cs, GazeBase.cs, and GazeHelper.cs.
- [] I have commented my code, particularly in hard-to-understand areas
> Remove deprecated sdk

- CognitiveVRUnity/Assets/CognitiveVR/Editor/InitWizard.cs
- CognitiveVRUnity/Assets/CognitiveVR/Scripts/CognitiveVR_Manager.cs
- CognitiveVRUnity/Assets/CognitiveVR/Scripts/FixationRecorder.cs
- CognitiveVRUnity/Assets/CognitiveVR/Scripts/GameplayReferences.cs
- CognitiveVRUnity/Assets/CognitiveVR/Scripts/GazeHelper.cs
Added support for Mixed Reality Toolkit 2.5.4 eye tracking for Hololens 2
Height Task ID (If applicable): T-771
> Added support for MRTK eye tracking

- Editor/DebugWindow.cs
- Editor/PreferencesInspector.cs
- Runtime/Internal/Cognitive3D_Preferences.cs
- Runtime/Internal/GazeCore.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- Runtime/Scripts/GPSLocation.cs
- Runtime/Scripts/GameplayReferences.cs
Moves all gps/geo location logic into Gameplay References class and wraps this with a C3D_LOCATION symbol. This should remove any permissions being added without explicit developer actions.
Also cleaned up related preferences and component.
> Location disable

- Editor/PreferencesInspector.cs
- Runtime/Components/ControllerInputTracker.cs
- Runtime/Internal/Cognitive3D_Preferences.cs
- Runtime/Scripts/DynamicObject.cs
- Runtime/Scripts/PhysicsGaze.cs
removed preferences for unsupported command buffer gaze feature.
removed web gateway options in preferences that are mostly internal use only
set dynamic object data id and custom id fields to private or internal to simplify the api
> Prefs cleanup

- Editor/EditorCore.cs
- Editor/ExitPollHolderInspector.cs
- Editor/ExportUtility.cs
- Editor/GLTF/GLTFSceneExporter.cs
- Editor/InitWizard.cs
- Editor/ManageDynamicObjects.cs
- Runtime/Internal/DynamicManager.cs
- Runtime/Scripts/GameplayReferences.cs
> Fix codacy issues

- Editor/EditorCore.cs
- Runtime/Components/OculusSocial.cs
- Runtime/Internal/Cognitive3D_Preferences.cs
- Runtime/Internal/DynamicManager.cs
- Runtime/Internal/Serialization/CoreInterface.cs
- Runtime/Internal/Serialization/SharedCore.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- Runtime/Scripts/DynamicObject.cs
- package.json
* Vive Wave 5.0.2 support
* MRTK support
* Location data now needs to be explicitly enabled
* API cleanup
* Various bug fixes
> version 1.0.1

- Runtime/Cognitive3D.asmdef
- Runtime/Components/ArmLength.cs
- Runtime/Components/BatteryLevel.cs
- Runtime/Components/Framerate.cs
- Runtime/Components/HMDHeight.cs
- Runtime/Components/HMDPresentEvent.cs
- Runtime/Components/OculusSocial.cs
- Runtime/Components/RoomSize.cs
- Runtime/ExitPoll/ExitPoll.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- Runtime/Scripts/FixationRecorder.cs
- Runtime/Scripts/GPSLocation.cs
- Runtime/Scripts/HPOmniceptSensors.cs
- [] Bug fix (non-breaking change which fixes an issue)
> Feature xrpf permissions

- Runtime/Internal/GazeCore.cs
> Ensuring floor isn't a dynamic object

- Editor/ManageDynamicObjects.cs
- Runtime/Scripts/DynamicObject.cs
* Merged 'Upload Mesh' and 'Upload Aggregation Ids' into a single button
* Added a popup prompt for exporting meshes
* Fixed filtering null reference caused by ID Pools
> Dynamic manager fix

- Runtime/Components/HMDPresentEvent.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
Height Task ID (If applicable):  https://c3d.height.app/T-1037
> Feature end session parameters

- Editor/EditorDataUploader.cs
- Runtime/Internal/NetworkManager.cs
> Propose update networkmanager

- Runtime/ActiveSessionView/Scripts/DataBatchCanvas.cs
- Runtime/ActiveSessionView/Scripts/EventCanvas.cs
- Runtime/Components/BoundaryEvent.cs
- Runtime/Components/Comfort.cs
- Runtime/Components/ControllerCollisionEvent.cs
- Runtime/Components/Framerate.cs
- Runtime/Components/HMDCollisionEvent.cs
- Runtime/Components/HMDPresentEvent.cs
- Runtime/Components/RecenterEvent.cs
- Runtime/Components/TeleportEvent.cs
- Runtime/ExitPoll/ExitPoll.cs
- Runtime/Internal/CustomEvent.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
Updated and Added more comments, especially around custom events
Fixed right controller state bug in ControllerCollisionEvent component
Added missing delegate clean up in Teleport and Recenter event components
> Cleanup delegates

- Runtime/Internal/DynamicManager.cs
- Runtime/Internal/GazeCore.cs
- Runtime/Internal/NetworkManager.cs
- Runtime/Internal/SensorRecorder.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- Runtime/Scripts/FixationRecorder.cs
* Handles cases where data would be serialized and sent to the dashboard while SceneId is null or empty
* Added limits to some repeating warnings
> Network response fix

- Editor/ExportUtility.cs
- Runtime/Cognitive3D.asmdef
- Runtime/Components/BatteryLevel.cs
- Runtime/Components/ControllerInputTracker.cs
- Runtime/Components/ControllerTracking.cs
- Runtime/Components/Framerate.cs
- Runtime/Internal/SensorRecorder.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- Runtime/Scripts/DynamicObject.cs
- Runtime/Scripts/FixationRecorder.cs
- Runtime/Scripts/GameplayReferences.cs
- Runtime/Scripts/HPOmniceptSensors.cs
* Controller input tracking component includes a session property
* Battery Level component handles sequential sessions
* Omnicept sensors component handle sequential sessions
* Room size minimum Z value no longer returns negative value
* Fixation recorder component in scene doesn't activate unless eye tracking is enabled for the project
* Framerate component logic refactor
* Omnicept session properties moved to Cognitive3d manager
* Scene export skips screen space canvases
* Added xr plugin provider session property
> Component fixes

- Runtime/Components/RoomSize.cs
Fix to indicate if roomsize is invalid
Height Task ID (If applicable): T-1988
> Invalid Room Size Fix

- Runtime/ExitPoll/ExitPollPanel.cs
Fix for scale based questions going outside the bounds of the panel as per Unity VSP report.
Height Task ID (If applicable): T-1942
- [] New feature (non-breaking change which adds functionality)
> Fixed scale out of panel bug

- Runtime/Cognitive3D.asmdef
- Runtime/Scripts/FixationRecorder.cs
- Runtime/Scripts/GazeHelper.cs
Fix for case where Pcio SDK generates compile errors for eye tracking.
Height Task ID (If applicable):  T-2043
> Proposed fixes for Sophia Pico

- Editor/Setup360Window.cs
- Runtime/Components/GazeSphere360.cs
Sphere will move with camera to ensure consistent gaze data on 360 video
Height Task ID (If applicable): T-1984
- [xx] My code follows the style guidelines of this project
> 360 Video Improvement

- Runtime/Internal/NetworkManager.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
Fixing errors to be more descriptive with recommended action for user.
Height Task ID (If applicable): https://c3d.height.app/T-1985
> Updated error logs to be more descriptive

- Runtime/Internal/DualFileCache.cs
Object disposed bug fixed (proposal)
Height Task ID (If applicable): T-1993
> Proposed fix for object disposed exception

- Runtime/Components/ControllerInputTracker.cs
- Runtime/Scripts/DynamicObject.cs
- Runtime/Scripts/GameplayReferences.cs
* Added support for Windows Mixed Reality, Pico and Focus controller inputs
* Various related controller fixes
Height Task ID (If applicable): T-1941
> Controller input naming fix

- Runtime/Components/ControllerTracking.cs
- Runtime/Scripts/GameplayReferences.cs
We want to check controller height for comfort. For now we can only check height relative to head.
> Feature comfort controller height

- Editor/EditorCore.cs
Some components/sensors were not being added to C3D Manager. Adding those in here. In addition, cleaning up some names.
> Adding more components to C3D Manager Instantiaion

- Runtime/Scripts/Cognitive3D_Manager.cs
Updating the use of deprecated functions.
Notion: https://www.notion.so/cognitive3d/Deprecated-CancelQuit-f84a92cfa910429b862cd8b4b9a62ec4?pvs=4
Height Task ID (If applicable): https://c3d.height.app/T-1855
> Using wantsToQuit() instead of CancelQuit()

- Editor/EditorCore.cs
- Editor/SceneSetupWindow.cs
- Runtime/Resources/Cognitive3D_Manager.prefab
Change to C3D_Manager to make it easier to update to our releases
- [] I have made corresponding changes to the documentation
> Updated C3D Manager to be a prefab

- Editor/ExitPollHolderInspector.cs
- Runtime/Components/RoomSize.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- Samples~/Ready Room/Editor/ReadyRoomSetupWindow.cs
- Samples~/Ready Room/SceneMenu/ISceneInfo.cs
- Samples~/Ready Room/SceneMenu/SceneLoadButton.cs
- Samples~/Ready Room/SceneMenu/SceneSelectMenu.cs
- Samples~/Ready Room/Scripts/AssessmentManager.cs
- package.json
* Fixed Ready Room namespace issues
* Removed unused variables
> 1.2.2 Release

- Editor/ControllerPointerEditor.cs
- Editor/ExitPollHolderInspector.cs
- Runtime/ExitPoll/ExitPoll.cs
- Runtime/Resources/ExitPollPointerLine_Focus.mat
- Runtime/Scripts/ControllerPointer.cs
Customer remarked that the curved pointer was confusing. I replaced that with a straight pointer. It is colored red, but turns green when focusing on a button. 
Try it out locally with an exit poll.
> Replaced curved pointer with color coded straigh pointer

- Runtime/ExitPoll/ExitPollHolder.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- Runtime/Scripts/DynamicObject.cs
Height Task ID (If applicable): https://c3d.height.app/T-3060 
https://c3d.height.app/T-3062
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
> Updated URL for HelpAttribute: DynamicObject, ExitPollHolder, C3DManager

- Editor/MediaComponentInspector.cs
- Editor/Setup360Window.cs
- Runtime/Scripts/MediaComponent.cs
- Runtime/Scripts/PhysicsGaze.cs
Renamed Media component's MediaSource field to MediaId for consistency.
> fixed consistency with mediaid field

- Runtime/Components/OculusHardware.cs
- Runtime/Components/RoomSize.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- Runtime/Scripts/GameplayReferences.cs
- Runtime/Scripts/GazeHelper.cs
- package.json
* Fix for Oculus SDK support for non-eyetracking headsets (ie Oculus Quest2)
* Fix for Oculus related sensors not serializing correctly
> Oculus eyetracking fix

- Runtime/Components/BatteryLevel.cs
Adding functionality to Battery Component to determine status of HMD Battery (charging -vs- not charging)
Testing Session: https://app.cognitive3d.com/scenes/010376d2-a7be-4692-9fea-36d92edc9722/v/19/session/900574
Height Task ID (If applicable): https://c3d.height.app/T-3397
> Sensor and CustomEvents for Battery Status

- Runtime/Components/ControllerInputTracker.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- Runtime/Scripts/GameplayReferences.cs
- Runtime/Scripts/GazeHelper.cs
- package.json
- pico eye tracking fix
- drag/drop on dynamic object window
- added battery status
- updating version numbers for Release `v1.3.2`
- [] New feature (non-breaking change which adds functionality)
> Release `1.3.2`

- Editor/Resources/WizardGUISkin.guiskin
- Editor/SceneSetupWindow.cs
- Runtime/Components/OculusSocial.cs
- Runtime/Resources/Cognitive3D_Manager.prefab
Height Task ID (If applicable): https://c3d.height.app/T-3837
- [x\] I have performed a self-review of my own code
> Retrieving user's Oculus ID, Username, and Display Name

- Runtime/Components/OculusSocial.cs
- Runtime/Resources/Cognitive3D_Manager.prefab
- Runtime/Resources/ExitPollScale.prefab
> ExitPoll Hotfix and OculusID improvement

- Runtime/Components/OculusSocial.cs
* Fixed writing session properties if the Oculus Platform is already initialized
* Changed AppId to automatically get the AppId from Unity's Platform Settings
Height Task ID (If applicable): T-4135
> Fix for OculusID if platform already initialized

- Editor/SceneSetupWindow.cs
- Runtime/Components/OculusPassthrough.cs
- Runtime/Components/OculusPassthrough.cs.meta
This change adds functionality to determine passthrough status in an application. We are sending the passthrough state as a sensor and also sending events when the state changes. Details on Notion: https://www.notion.so/cognitive3d/Meta-Passthrough-ea4942ce1b184e958ffdd991fb3bbe09?pvs=4
Height Task ID (If applicable): https://c3d.height.app/T-4347
> Oculus Passthrough Feature + Setup Improvement for Quest Features

- .github/PULL_REQUEST_TEMPLATE.md
> updated PR template with instructions, additional checklist items, fixed markdown formatting

- Editor/ProjectSetupWindow.cs
- Checks for JSON response validity
- Logs an error if JSON response is invalid
- Displays a message on the onboarding window if JSON response is invalid
- Changes are made in ProjectSetupWindow.cs
Height Task ID (If applicable): https://c3d.height.app/T-4464
> Fix for invalid JSON response from getting Developer Key

- Runtime/Internal/DynamicManager.cs
- Runtime/Scripts/DynamicObject.cs
Added functions Dynamic Objects to better support in-app creation tools. Specifically:
* Resetting an internal list of Dynamic Objects
* Immediately removing Dynamic Object data from an internal list if a session is not active
* Setting CustomID and MeshNames on Dynamic Objects and updating their data on an internal list
> Dynamic id source fixes

- Runtime/Components/RoomTrackingSpace.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- package.json
Changing the version number on `Cognitive3D_Manager` and `package.json` for release `1.4.0`. This release contains a hot fix for failing `OculusSocial.cs` causing missing session data and zero data.
Changes:
- Fixed `OculusSocial.cs` to handle exceptions better
> Release `1.4.0`

- Runtime/Components/ProfilerSensor.cs
- Runtime/Components/ProfilerSensor.cs.meta
- Runtime/Resources/Cognitive3D_Manager.prefab
Sending sensor values for the following profiler data points:
- Number of draw calls
- System memory usage (we are sending in MB)
- Main Thread Time (we are sending in milliseconds)
Height Task ID(s) (If applicable): https://c3d.height.app/T-4195
> Profiler API Sensor Stream

- Runtime/Components/HMDOrientation.cs
Updating HMDPitch to use tracking space as a reference
Height Task ID(s) (If applicable): https://c3d.height.app/T-2566
> Fix to HMD Pitch Calculation

- Runtime/Components/BatteryLevel.cs
- Runtime/Components/HandTracking.cs
- Runtime/Components/OculusPassthrough.cs
- Runtime/Components/ProfilerSensor.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
Changes to sensor frequency:
- Changed BatteryLevel to 0.1Hz
- Changed HandTracking to 1Hz
- Changed Passthrough to 1Hz
Removed BatteryLevel from `c3d.sessionStart`
Height Task ID(s) (If applicable): https://c3d.height.app/T-4858, https://c3d.height.app/current-sprint/T-4900, https://c3d.height.app/current-sprint/T-4898, https://c3d.height.app/current-sprint/T-4903
> Increasing Sensor Frequency and removing battery from session start

- Editor/EditorDataUploader.cs
- Moved log messages for clearing the cache in the editor to logDevelopment
Height Task ID(s) (If applicable): https://c3d.height.app/T-5251
> Logging debug messages for editor cache upload under logDevelopment

- Runtime/Cognitive3D.asmdef
- Runtime/Components/PhotonMultiplayer.cs
- Runtime/Components/PhotonMultiplayer.cs.meta
- Runtime/Internal/Serialization/SharedCore.cs
- Runtime/Resources/Cognitive3D_Manager.prefab
Events for create and join and sensors for RTT and RTT variance
> Create join events

- Editor/SceneSetupWindow.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
The Scene Setup Window was initializing a non-prefab version of the Cognitive3D_Manager. This PR fixes that.
Height Task ID(s) (If applicable): https://c3d.height.app/T-6627
> Fixing instantiation of non-prefab C3D_Manager

- Editor/ExportUtility.cs
- Editor/GLTF/GLTFSceneExporter.cs
Include support for exporting Sprite Renderers using a baked texture and a quad similar to Canvas export
Height Task ID(s) (If applicable): T-5815
> Sprite Renderer Export

- Editor/EditorCore.cs
- Editor/ProjectValidation/Items/ProjectValidationItems.cs
- Editor/ProjectValidation/ProjectValidationGUI.cs
The following changes have been made for Vive Wave SDK validation items:
- Added a required validation item to ensure the `Wave Rig` component exists in the scene.
- Added a recommended validation item to suggest setting the tracking origin to `Floor` within the Wave Rig component.
**Note: These changes are related to Project Validation and may impact the automated build processes.**
Height Task ID(s) (If applicable): https://c3d.height.app/T-7075
- [N/A] I have checked all outgoing links (i.e. to documentation) for validity
> Vive Wave SDK validation items

- Editor/DynamicObjectInspector.cs
- Editor/ExportUtility.cs
- Editor/ProjectValidation/Items/ProjectValidationItemsStatus.cs
- Editor/SceneSetupWindow.cs
- Runtime/Components/HMDHeight.cs
- Runtime/Internal/DualFileCache.cs
- Runtime/Internal/Serialization/SharedCore.cs
- Runtime/Scripts/Cognitive3D_Manager.cs
- package.json
Fixed Bugs:
* Fixed Sensors not writing empty arrays
* Fixed rare case where local cache wasn't sending data without restarting a session
* Fixed Project Validation asks user to save scene before validation
* Exporting canvas fixes
* Exporting sprite fixes
* Fixed UI bug with uploading dynamic object ids from the inspector
Height Task ID(s) (If applicable):
> Unity SDK Release 1.5.1

- Editor/DynamicObjectsWindow.cs
- Editor/EditorCore.cs
- Editor/ExportUtility.cs
- Editor/HelpWindow.cs
- Editor/ProjectSetupWindow.cs
- Editor/ProjectValidation/ProjectValidationSettingsProvider.cs
- Editor/SceneManagementWindow.cs
- Editor/SceneSetupWindow.cs
- Editor/SegmentAnalytics.cs
The following updates have been made to enhance Segment Analytics:
- Included scene version in the scene setup page where users upload a new scene with related data being sent.
- Added logic for user identification to associate users with their organization name and track the actions they take.
Height Task ID(s) (If applicable): https://c3d.height.app/T-10019 & https://c3d.height.app/T-10341
> Segment Improvement
